import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Luana e Matheus - 3 de janeiro de 2026",
  // description: "Generated by create next ap",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
